### PR TITLE
German translation

### LINKED ISSUE #2825: Translate the App into German
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

I would love to see a German translation in the app. German is quite a big language in central europe and i think i am not the only one who would like to change the language to German.

I have seen that there were issues created before (#429 & #1805) regarding a german translation, but they were closed without any comment. Is there a specific reason for that?

Anyhow, if this gets approved i might start translating today.

### Why do you need it?

- If the language can be changed to your native language, it is easier for many people to find their way around the app.

### How do you imagine it?

_No response_

### PR DESCRIPTION
**Pull request by CedricLindigkeit**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the "Contributing Rules".
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

https://github.com/Ivy-Apps/ivy-wallet/assets/68247763/2c9fecfe-ab81-4c28-bd3c-4e918e00cf5b

## What's changed?

Tip: you can attach screenshots using a markdown table.

 

 

 

 

  

 

 

 

|:----------|:----------|:----------|:----------|:----------|:----------|:----------|:----------|:----------|:-----------|

  

 

 

Describe with a few bullets **what's new:**
- Translated every NOT HARDCODED string into German
> 💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!

## Risk Factors

**What may go wrong if we merge your PR?**

- Nothing

**In what cases your code won't work?**

- It does work. Keep in mind hardcoded strings HAVE NOT been translated

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2825 

> Replace `ISSUE_NUMBER` with your issue number (for example Closes #1234). If you've done that correctly, you'll see the issue title linked when previewing your PR description.

## Troubleshooting CI failures

If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or simply click "Details" next to the failed check and explore the logs to see why it has failed.

### Detekt
[Detekt](https://detekt.dev/) is a static code analyzer for Kotlin that we use to enforce code readibility and good practices.

**To run Detekt locally:**
```
./gradlew detekt
```

If the Detekt errors are caused by a legacy code, you can suppress them using a basline.

**Detekt baseline** (not recommended)
```
./scripts/detektBaseline.sh
```

### Lint

We use the [standard Android Lint](https://developer.android.com/studio/write/lint) plus [Slack's compose-lints](https://slackhq.github.io/compose-lints/) as an addition to enforce proper Compose usage.

**To run Lint locally:**
```
./scripts/lint.sh
```

If the Lint errors are caused by a legacy code, you can suppress them using a basline.

**Lint baseline** (not recommended)
```
./scripts/lintBaseline.sh
```

### Unit tests

If this job is failing this means that your changes break an existing unit test. You must identify the failing tests and fix your code.

**To run the Unit tests locally:**
```
./gradlew testDebugUnitTest
```

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
I don't understand German but seems like an excellent work!! 👏 Thanks for including all these screenshots 💯

**Comment by ILIYANGERMANOV** [comment]
CI is failing, ping me when you resolve it so we can merge the PR 👍

**Comment by CedricLindigkeit** [comment]
I can't figure out what's going wrong right now, so I might check again tomorrow.

"It works on my machine"™ - The same tasks are successful on my computer .-.

**Comment by ILIYANGERMANOV** [comment]
No rush^ Just make sure to comment if the PR get automatically marked as "Stale"

**Comment by CedricLindigkeit** [comment]
Found the issue: Android Resource Linking fails.

Don't know what's causing this yet, but maybe I'll find out.

**Comment by ILIYANGERMANOV** [comment]
Removed Stale label

**Pull request closed without merging**
