### PR TITLE
Fix issue 2869

### LINKED ISSUE #2869: Loans' missing date
When creating a Loan, if you don't create a transaction associated with it, there's no way to tell when that loan was created

The solution would be to add the date of creation somewhere on the interface

### PR DESCRIPTION
**Pull request by beradeep**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the "Contributing Rules".
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] 🎬 I've attached a **screen recoding** of the changes. 

## What's changed?

 | 
---|---

Describe with a few bullets **what's new:**
- added date feature to loans
- configured its editability
- updated db from v123-v124 using proper migration 

## Does this PR closes any GitHub Issues?

- Closes #2869

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
Didn't review much in detail but LGTM! A few things before being ready to merge:
- We need ✅ on all CI checks. If the Detekt errors are caused by the legacy code and too much, you can a Detekt baseline.
- Fix the unused imports Detekt problems
- I'll test the DB migration when the APK is ready.

Nice work 💯

**Comment by ILIYANGERMANOV** [comment]
Hey @beradeep it's probably something with the date - can you make a bugfix PR? Thanks for reporting @nvllz!! 🙏 Great catch

**Comment by beradeep** [comment]
Sure, I'll look into it. Thanks for the report @nvllz.

**Comment by ILIYANGERMANOV** [comment]
Hey @beradeep the fix is to:
- make the Loan datetime nullable for backwards compatibility
- write some export & import logic in the `BackupLogic.kt` so this date can be backed up, too

**Pull request merged**
