### PR TITLE
[#2037] fixed username text

### PR DESCRIPTION
**Pull request by FielderNik**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] My code builds and is tested on a real Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

## What's changed?

Describe with a few bullets **what's new:**

fixed username text

Screenshot_20230916_233710

## Risk Factors

**What may go wrong if we merge your PR?**

- a
- b
- c

**In what cases your code won't work?**

- a
- b
- c

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #{ISSUE_NUMBER}

_Replace `{ISSUE_NUMBER}` with the id/number of the issue that you've fixed._

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
LGTM! Thank you for fixing it 💯 Keep in mind that since your editing legacy code "Detekt" and/or "Lint" may complain, we'll see. If they do and the errors are too hard to fix, feel free to add baslines.

**Detekt:**
```
./gradlew detektBaseline
```

**Lint:**
```
./gradlew lintR
```

**Comment by ILIYANGERMANOV** [comment]
Hey @FielderNik seems like there are only a few Detekt errors:
```
Property 'style>OptionalWhenBraces' is deprecated. Same functionality is implemented in BracesOnWhenStatements.
/home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:9:1: Wildcard import [NoWildcardImports]
/home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:192:69: Unexpected blank line(s) before "}" [NoBlankLineBeforeRbrace]
/home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:128:8: First line in a method block should not be empty [NoEmptyFirstLineInMethodBlock]
/home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:9:1: androidx.compose.foundation.layout.* is a wildcard import. Replace it with fully qualified imports. [WildcardImport]
```

Can you please fix them and we can merge?

**Comment by FielderNik** [comment]
> Hey @FielderNik seems like there are only a few Detekt errors:
> 
> ```
> Property 'style>OptionalWhenBraces' is deprecated. Same functionality is implemented in BracesOnWhenStatements.
> /home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:9:1: Wildcard import [NoWildcardImports]
> /home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:192:69: Unexpected blank line(s) before "}" [NoBlankLineBeforeRbrace]
> /home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:128:8: First line in a method block should not be empty [NoEmptyFirstLineInMethodBlock]
> /home/runner/work/ivy-wallet/ivy-wallet/screen-home/src/main/java/com/ivy/home/HomeHeader.kt:9:1: androidx.compose.foundation.layout.* is a wildcard import. Replace it with fully qualified imports. [WildcardImport]
> ```
> 
> Can you please fix them and we can merge?

done

**Comment by ILIYANGERMANOV** [comment]
Thank you! To check if Detekt pass locally run:
```
./gradlew detekt
```
Merging after the CI pass ✅

**Pull request merged**
