### PR TITLE
Fixed some formatting errors from detekt.

### LINKED ISSUE #2782: I'd like to find a way to conceal, blur, or encrypt my income information from the home page.
Because There are some moments when I'm hesitant to open this app in certain places like front of colleges or family. I've noticed there's already an option for cash flow; I believe a similar feature could be implemented for income as well.

### PR DESCRIPTION
**Pull request by venumanas87**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the "Contributing Rules".
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?

Describe with a few bullets **what's new:**
- a ) Now the users can hide income in homescreen (similar to hide balance functionality) by changing it from settings screeen.

> 💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!

https://github.com/Ivy-Apps/ivy-wallet/assets/62274718/59983bb8-aef8-414a-a448-e22d2b6cc3d1

## Risk Factors

**What may go wrong if we merge your PR?**

- a)  All tests are passed and no major changes so not a possibility of going wrong.

**In what cases your code won't work?**

- a)  The code will work in all edge cases.

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2782 

> Replace `ISSUE_NUMBER` with your issue number (for example Closes #1234). If you've done that correctly, you'll see the issue title linked when previewing your PR description.

## Troubleshooting CI failures

If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or simply click "Details" next to the failed check and explore the logs to see why it has failed.

### Detekt
[Detekt](https://detekt.dev/) is a static code analyzer for Kotlin that we use to enforce code readibility and good practices.

**To run Detekt locally:**
```
./gradlew detekt
```

If the Detekt errors are caused by a legacy code, you can suppress them using a basline.

**Detekt baseline** (not recommended)
```
./scripts/detektBaseline.sh
```

### Lint

We use the [standard Android Lint](https://developer.android.com/studio/write/lint) plus [Slack's compose-lints](https://slackhq.github.io/compose-lints/) as an addition to enforce proper Compose usage.

**To run Lint locally:**
```
./scripts/lint.sh
```

If the Lint errors are caused by a legacy code, you can suppress them using a basline.

**Lint baseline** (not recommended)
```
./scripts/lintBaseline.sh
```

### Unit tests

If this job is failing this means that your changes break an existing unit test. You must identify the failing tests and fix your code.

**To run the Unit tests locally:**
```
./gradlew testDebugUnitTest
```

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
LGTM! Fix the CI errors and we can merge ✅

**Comment by ILIYANGERMANOV** [comment]
Detekt Errors to fix:
- unused imports 
- then add a Detekt baseline for the LongParametersList

**Comment by venumanas87** [comment]
> LGTM! Fix the CI errors and we can merge ✅

Sure on it

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV  Can you please help me out in this issue when script tries to run
> ` ./gradlew detektBaseline`  it throwing an error which looks like this -:
> 
> >  Cannot access input property 'source' of task ':detektBaseline'. Accessing unreadable inputs or outputs is not supported. Declare the task as untracked by using Task.doNotTrackState(). For more information, please refer to https://docs.gradle.org/8.4/userguide/incremental_build.html#disable-state-tracking in the Gradle documentation.
> 

No idea, works on my machine 😀 Jk, what OS are you using?

**Comment by venumanas87** [comment]
windows

**Comment by venumanas87** [comment]
Should I go for the manual process of updating the baseline.yml file?🥲

**Comment by ILIYANGERMANOV** [comment]
> Should I go for the manual process of updating the baseline.yml file?🥲

Please do so, no idea how to fix it. You can ChatGPT to fix the script on Windows

**Comment by venumanas87** [comment]
Okay

**Comment by venumanas87** [comment]
Somehow fixed the detekt baseline🥲

**Comment by ILIYANGERMANOV** [comment]
Nice 🎉 400+ files changed, I see that Detekt made some auto-format. Updated the branch and merging after the CI pass of up-to-date main. Great job!

**Comment by venumanas87** [comment]
> Nice 🎉 400+ files changed, I see that Detekt made some auto-format. Updated the branch and merging after the CI pass of up-to-date main. Great job!

Thanks 🤞

**Pull request merged**
