### PR TITLE
Aadhithya d fix issue 117

### LINKED ISSUE #117: Add quick settings title support
**What do you want to be added or improved?**
As a user I want to be able to add an expenses directly from the quick settings menu via a title directly.

**Is your request already listed in [Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)?**
- [ ] Yes, it already exists.
- [x] No, it's a new issue.
- [ ] I'm not sure but I've checked.

_Put an `x` in the boxes that apply._

- [x] Demo: Checking checkbox using `[x]`

**Explain with bullets why do you need it**
- a_ it makes it easier and faster to enter the expenses.

**Explain how do you imagine it in detail**
Write any implementation details that might help us better fulfill your feature request.
**I'd like to:**
- a_ a title in the quick settings menu, i press it, and then this menu appears to me 
- 
Screenshot_20211112-183552_Ivy_Wallet

### PR DESCRIPTION
**Pull request by Aadhithya-D**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the "Contributing Rules".
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

## What's changed?
QuickTile Ivy Wallet jpg

Describe with a few bullets **what's new:**
- a) Added QuickTile Support
- b) Click QuickTile to open payments page in the app

https://github.com/Ivy-Apps/ivy-wallet/assets/68938605/d8365366-3861-4009-a2ea-bc7b2d48763a

## Risk Factors

**What may go wrong if we merge your PR?**

- a) Nothing

**In what cases your code won't work?**

- a) It will work.

## Does this PR closes any GitHub Issues? 
Yes

- Closes #117

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
Excellent work!

**Comment by ILIYANGERMANOV** [comment]
@Aadhithya-D fix the Detekt errors and make sure the CI pass and we're good to merge ✅️ It seems like a bunch of unused imports

**Comment by Aadhithya-D** [comment]
@ILIYANGERMANOV I have fixed Detekt errors, should I close this PR and create a new one?

**Comment by ILIYANGERMANOV** [comment]
Merged :tada:

**Pull request merged**
