### PR TITLE
PR template - dev exp enhancements

### LINKED ISSUE #3335: Fix PR template code view
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

- Remove any not required blank lines
- Make tips and other comments more stand out from main body of PR

### Because...

- For better developer experience

### Description

_No response_

### Success Criteria

_No response_

### PR DESCRIPTION
**Pull request by CodinGeo**
## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [ ] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## What's changed?
Describe with a few bullets **what's new:**

- Deleted `main` branch checkbox
- In code view: deleted unnecessary empty lines, clarified comments

Before|After
-------|-------
image|image
image|image
image|image
image| 

## Risk factors

**What may go wrong if we merge your PR?**

- People still might be confused

**In what cases won't your code work?**

- It's a doc

## Does this PR close any GitHub issues?

- Closes #3335

## Troubleshooting CI failures ❌

Pull request checks failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

**Comment by CodinGeo** [comment]
Actually while making this PR I also was confused when the commented table wasn't showing up lol.

**Review by ILIYANGERMANOV — APPROVED** [review]
Looks great! 💯

**Comment by ILIYANGERMANOV** [comment]
@CodinGeo amazing work with our docs and templates 👏 Now, they are 100x nicer! If you're interested, can you also improve our Bug, Feature and Dev request templates. Currently, they're a bit confusing

**Comment by CodinGeo** [comment]
@ILIYANGERMANOV I'm glad You enjoy them, I hope other contributors will as well :). I thought about giving myself a break in order to end development of my own project, but then I could maybe contribute to Ivy Wallet's website, as front-end is probably the thing that would fit me more in the long run. Do you think there is a need for someone to take care of it a bit more?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV I'm glad You enjoy them, I hope other contributors will as well :). I thought about giving myself a break in order to end development of my own project, but then I could maybe contribute to Ivy Wallet's website, as front-end is probably the thing that would fit me more in the long run. Do you think there is a need for someone to take care of it a bit more?

No worries, take your time! Nah, they're not urgent. Best of luck with your project! 🙌 Thanks again for your contributions! I'll test the updated PR template and see if contributors are more inclined to fill it. (if not a PR description CI check incoming) 😅

**Pull request merged**
