### PR TITLE
Added zh_TW translation

### PR DESCRIPTION
**Pull request by shinebrillant**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [ ] I confirm that I've run the code locally and everything works as expected.
- [ ] 🎬 I've attached a **screen recoding** of the changes.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).

## What's changed?
Added Traditional Chinese translation

## What do you want to be added or improved?
The left is a user. I have Traditional Chinese needs.

## Why do you need it?
Make it available to more people

## How do you imagine it?
I can help translate into Traditional Chinese

### CODE REVIEW

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
The app doesn't build and the CI fails. If you have Android Studio it'll be easier to see why it fails,.otherwise try ChatGPT it should be capable to fix it

**Comment by ILIYANGERMANOV** [comment]
I found the error from the logs:

* What went wrong:
Execution failed for task ':shared:ui:core:packageReleaseResources'.
> /home/runner/work/ivy-wallet/ivy-wallet/shared/ui/core/src/main/res/values-zh-TW: Error: Invalid resource directory name

**Comment by ILIYANGERMANOV** [comment]
@shinebrillant the solution would be to rename the folder to:
```
src/main/res/values-zh-rTW/
```

Screenshot_20240708_163114_ChatGPT

**Review by ILIYANGERMANOV — APPROVED** [review]
Nice work! Thanks for translating the app 💯 Merging after the CI passes successfully

**Comment by shinebrillant** [comment]
Thank you so much.

**Pull request merged**
