### PR TITLE
Add vietnamese translation, add new key string for some hardcode text…

### LINKED ISSUE #3087: [FEATURE] Vietnamese Language Support
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want a version that supports Vietnamese

### Why do you need it?

Expand the scope of users because I have seen on Google Play Store that there are requests for the Vietnamese version

### How do you imagine it?

All text in the app will have a Vietnamese version, i will take care of the transaltion

### PR DESCRIPTION
**Pull request by isaacnguyen0809**
…, remove redundant key, fix padding and text style

## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] 🎬 I've attached a **screen recoding** of the changes. 

## What's changed?
Add Vietnamese translation

## Screenshot
Screenshot_20240406_022612
Screenshot_20240406_022642

Describe with a few bullets **what's new:**
- Remove redundant key string(Some strings have the same data but different keys)
- Key definitions for some strings are still hardcoded
- Slightly edited the interface and style of the text

## Risk Factors
No

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #3087

### CODE REVIEW

**Review by ILIYANGERMANOV — COMMENTED** [review]
Hey @isaacnguyen0809 a few things:
- Update branch
- Fix Detekt

There might make sense some strings to be duplicated if in future we want to provide different texts for the different screens. Use common sense and your best judgment

**Comment by isaacnguyen0809** [comment]
@ILIYANGERMANOV some updates

- I fixed the detekt in 1 place, but the remaining 3 places are quite large, so I think i won't touch this part in this PR because it will have to refactor the function a lot and I'm afraid it will have a big impact.(Can we skip this part in this PR :D)-(image below)

image

- Regarding duplicate strings, I justa accidently found one, and I believe it is redundant because the two uses have the same UI, the same text data but different key strings.(image below)

image
image

**Comment by ILIYANGERMANOV** [comment]
@isaacnguyen0809 use `@Suppress`
https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md#detekt

**Review by ILIYANGERMANOV — APPROVED** [review]
Nice work 💯 Fix the Detekt using `@Suppress` and we can merge

**Pull request merged**
