### PR TITLE
Fix issue #3011

### LINKED ISSUE #3011: [BUG] Search View Clear button is Gone upon long query text
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When user searches in search view if that search query is to long, clear button is gone

### To Reproduce

1. Go to search screen
2. search long  query text
3. observe clear button is now gone

### Expected behavior

Clear button should always visible irrespective of query length

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/68009703/536ef0a4-b5b0-49d2-bc26-a378dbb05b42

### Smartphone

Samsung S23

### Additional context

Have fixed this

### PR DESCRIPTION
**Pull request by Natzee**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [Y] The PR is submitted to the `main` branch.
- [Y ] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [ Y] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [ Y] I confirm that I've run the code locally and everything works as expected.
- [ Y] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?
1.Global search
2.Exchange rate screen
3.Search tags screen

## Does this PR closes any GitHub Issues? Yes
Screenshot_20240308-163259
Screenshot_20240308-163323
Screenshot_20240308-163349

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #3011 

> Replace `3011` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.

> **!Note:** Do **not** link the PR number. Link the number/id of the GitHub Issue from [issues](https://github.com/Ivy-Apps/ivy-wallet/issues).

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]

**Comment by ILIYANGERMANOV** [comment]
Nice work 💯 Merging after the CI pass ✅

**Comment by ILIYANGERMANOV** [comment]
@Natzee ping me when you fix the CI errros

**Comment by ILIYANGERMANOV** [comment]
Feel free to suppress the MagicNumber error

**Comment by Natzee** [comment]
@ILIYANGERMANOV Have resolved magical number  fix

**Pull request merged**
