### PR TITLE
Added min width to outline button

### LINKED ISSUE #2683: Swiping Action Improvement
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.

### What would you like to improve?

I want to improve the monthly swiping action

### Because...

It causes a problem where you swipe into the accounts section by accident

https://github.com/Ivy-Apps/ivy-wallet/assets/113838259/365fffb8-cedd-47d0-8816-72b42931fdbd

### Description

_No response_

### Success Criteria

Add "minWidth = X.dp" to the button

### PR DESCRIPTION
**Pull request by parvinder8**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [ ] The PR is submitted to the `main` branch.
- [ ] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
- [ ] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [ ] My code builds and is tested on a real Android device.
- [ ] I confirm that I've run the code locally and everything works as expected.

## What's changed?

https://github.com/Ivy-Apps/ivy-wallet/assets/107536472/50cd08fa-c600-477c-be17-6fa8b1ee28dd

--> Added min width to button 

## Does this PR closes any GitHub Issues?

Check https://github.com/Ivy-Apps/ivy-wallet/issues/2683

- Closes #2683

### CODE REVIEW

**Comment by parvinder8** [comment]
@ILIYANGERMANOV should i adjust size for big month names also ?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV should i adjust size for big month names also ?

Hey @parvinder8 you should make the button content look centered first. The big months are okay and they shouldn't be affected by the minWidth

**Comment by ILIYANGERMANOV** [comment]
@parvinder8 let's also lower the `minWidth` to let's say 128.dp or less cuz the "Hi UserFirstName..." won't fit well.

**Comment by parvinder8** [comment]
DONE 

https://github.com/Ivy-Apps/ivy-wallet/assets/107536472/c9594786-88ad-47fd-8b4d-be1a38887b41

**Review by ILIYANGERMANOV — APPROVED** [review]
Looks good! Thank you Parvinder 🎉

I see that Lint is failing because of the legacy code. Run
```
./scripts/lintBasline.sh
```
and then "git push" to fix that.

**Comment by ILIYANGERMANOV** [comment]
Hey @parvinder8 let me know if you have any issues creating the Lint baseline using the script

**Comment by ILIYANGERMANOV** [comment]
Hey @parvinder8 lint still fails. Did the `./script/lintBaseline.sh` finished successfully? It seems like it didn't because our script makes an automatic commint with "Update Lint baseline" msg.

**Comment by parvinder8** [comment]
yes it failed. its giving environment java home error

**Comment by ILIYANGERMANOV** [comment]
> yes it failed. its giving environment java home error

got it @parvinder8 then do the follow run 2 twice:
```
./gradlew lintR
```

this should generate the baseline. The final step would be to commit the baseline. 
If that doesn't work try to fix your Java error. You need Java 17+ installed on your machine.

**Comment by ILIYANGERMANOV** [comment]
Nice - we're almost there! The last rhing you need is to rebase/update your branch because there's a merge conflict

**Comment by ILIYANGERMANOV** [comment]
> getting conflict in lint baseline. how to solve it ?

Accept whatever in the baseline. Or simply delete all contents of the baseline.
Then run the:
`scripts/lintBasline.sh`

to regenerate it again and you should be good.


Or I can resolve the conflict for you and you can do just `git pull`

**Comment by ILIYANGERMANOV** [comment]
Hey @parvinder8 use this https://github.com/Ivy-Apps/ivy-wallet/pull/2686/conflicts to resolve conflicts.
Then run:
```
./scripts/lintBaseline.sh
```

And then we'll be good to merge it after the CI pass ✅

**Comment by ILIYANGERMANOV** [comment]
Hey @parvinder8 something is wrong with the rebase, 111 files changed and 25 commits. The branch got messed up.

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
Rebase problem - 111 filee changed.

**Comment by ILIYANGERMANOV** [comment]
It seems that you've rebased on an outdated `main` on your fork. 
To fix it:
1. Sync your fork
2. Pull the latest `main` in your fork
3. Rebase again

**Comment by parvinder8** [comment]
finally completed....

**Comment by ILIYANGERMANOV** [comment]
> finally completed....

Unfortunately, the branch is still messed up. **126 files changed**, something went wrong with your forked branch. I'd suggest to start over in a fresh branch.

**Pull request closed without merging**
