### PR TITLE
Add Mongolian language strings

### LINKED ISSUE #2315: [FEATURES] Mongolian language `mn`
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a user I want to have Mongolian language user interface

### Why do you need it?

- Add `mn` localization to Ivy Wallet app

### How do you imagine it?

Add new localization for `mn`

### PR DESCRIPTION
**Pull request by sadespresso**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on a real Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

## What's changed?
Describe with a few bullets **what's new:**
- Added `values-mn/strings.xml` for Mongolian translation

## Risk Factors

**What may go wrong if we merge your PR?**

- Nothing

**In what cases your code won't work?**

- None

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2315

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
Nice 💯  Thank you @sadespresso! Can you test the app with the apk with the "APK" GitHub Action and upload a screen recording?

Sometimes for some languages key features like adding transactions stops working, the app crashes randomly or the UI breaks. So I'd appreciate to test the app with obfuscated APK from the workflow and attach it here. The more features you test with Mongolian the higher confidence will have

**Comment by sadespresso** [comment]
Thank you for the quick response!

Of course! I will provide a screen recording ASAP.

**Comment by sadespresso** [comment]
I used the apk artifact from the action. <https://github.com/Ivy-Apps/ivy-wallet/actions/runs/6106559085/>

First one is reinstalling with existing data (residue from debug mode)
<https://youtu.be/oJpVNCntrgE>

This one is fresh demo install
<https://youtu.be/YJfgBOOjzM0>

**Comment by sadespresso** [comment]
P.S. The video size was too big I had to upload to YouTube

**Review by ILIYANGERMANOV — APPROVED** [review]
Excellent work! 💯 Thank you for providing all the videos 👏 Much appreciated - merging into `main` 🎉

**Pull request merged**
