### PR TITLE
Fix issue 2702

### LINKED ISSUE #2702: Toggle to see percent vs amount on Loan[FEATURE]
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I want to see the actual amount (with respect to the loan repaid percentage).

### Why do you need it?

- It can be pretty convenient to see how much total money I've spent on loan repayment.

### How do you imagine it?

So I see two option here-

1. Give an option to toggle b/w percent & actual amount on loan screen (As I see a lot of empty space there).
2. Go via settings and have a dedicated option for loans there. And we can toggle & control this scenario.

Pros with 1st- Quite convenient & user can easily toggle between the two options. It can be a good UX.
Pros with 2nd- We can incorporate more customisations with Loan Listing Experience. eg. [2691](https://github.com/Ivy-Apps/ivy-wallet/issues/2691)

### PR DESCRIPTION
**Pull request by vartult**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] My code builds and is tested on a real Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

## What's changed?
totalPendingAmount

Describe things in a short and straightforward manner.
--> This feature addition will help user track the total owe and owed amount.

Describe with a few bullets **what's new:**
- User can track Owe Amount
- User can track Owed Amount
- If any any of the amount be zero (No Lent/Borrow Present) that field won't be visible

## Does this PR closes any GitHub Issues?

Check **[2702](https://github.com/Ivy-Apps/ivy-wallet/issues/2702)**.

- Closes #2702

_Replace `{2702}` with the id/number of the issue that you've fixed._

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
**Detekt errors:** (styling only)

/home/runner/work/ivy-wallet/ivy-wallet/screen-loans/src/main/java/com/ivy/loans/loan/LoanViewModel.kt:132:16: Missing { ... } [MultiLineIfElse]
/home/runner/work/ivy-wallet/ivy-wallet/screen-loans/src/main/java/com/ivy/loans/loan/LoanViewModel.kt:138:16: Missing { ... } [MultiLineIfElse]
/home/runner/work/ivy-wallet/ivy-wallet/screen-loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt:207:17: Missing { ... } [MultiLineIfElse]
FAILURE: Build failed with an exception.

/home/runner/work/ivy-wallet/ivy-wallet/screen-loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt:215:17: Missing { ... } [MultiLineIfElse]
* What went wrong:

**Review by ILIYANGERMANOV — APPROVED** [review]
LGTM! Thank you! Fix Detekt and we're ready to merge 🎉

**Comment by ILIYANGERMANOV** [comment]
@vartult to fix Detekt you need style your if like:
```
if (condition) {
  a
} else {
  b
}
```

**Comment by ILIYANGERMANOV** [comment]
I edited the PR description to:
- Closes #2702 so it can auto-close the issue when the PR is merged

**Comment by ILIYANGERMANOV** [comment]
@vartult some more Detekt:
mplemented in BracesOnWhenStatements.
/home/runner/work/ivy-wallet/ivy-wallet/screen-loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt:207:21: Argument should be on a separate line (unless all arguments can fit a single line) [ArgumentListWrapping]

FAILURE: Build failed with an exception.
/home/runner/work/ivy-wallet/ivy-wallet/screen-loans/src/main/java/com/ivy/loans/loan/LoansScreen.kt:214:21: Argument should be on a separate line (unless all arguments can fit a single line) [ArgumentListWrapping]


---

You can run:
```
./gradlew detekt
```

to see and fix errors locally fast

**Comment by vartult** [comment]
Sure looking into it, seems like my linter is not setup properly as per the project.

**Comment by ILIYANGERMANOV** [comment]
> Sure looking into it, seems like my linter is not setup properly as per the project.

You can try to run:
```
./scripts/detektFormat.sh
```

**Comment by ILIYANGERMANOV** [comment]
> Sure looking into it, seems like my linter is not setup properly as per the project.

Let us know if and how we can configure Android Studio auto-formating to match Detekt style

**Pull request merged**
