### PR TITLE
Refactor TransactionCard UI to support compactMode

### LINKED ISSUE #3498: Add Compact-Sized Transaction Cards with Toggle Option
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user I would like to request the addition of compact-sized transaction cards, similar to the existing category and account cards. It would be helpful if this feature could include a toggle option in the advanced settings, allowing users to switch between the default and compact views. This enhancement would provide more flexibility and improve the user experience by enabling more efficient transaction management in a condensed format.

### Why do you need it?

_No response_

### How do you imagine it?

_No response_

### PR DESCRIPTION
**Pull request by p42rthicle**
## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [x] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## Screen recording of your changes (if applicable):
https://github.com/user-attachments/assets/7935fc05-dcc8-4958-a140-28d38f683b27

## What's changed?

Describe with a few bullets **what's new:**
- I've refactored the transaction card to support compact mode.
- In the compact mode, the transaction card does not show
  - The account badges 
  - Categories badges
  - Tags row
  - Description
- Hides the due date and the Skip or Pay/Get buttons in a toggleable expand icon
- I have refactored the components into individual reusable composables for better readability and understanding of the file
- The `TypeAmountCurrency` in the non-compact card is also now `TitleTypeAmountCurrencyRow` just without showing the title
- Have handled cases when the user might enter huge currency or huge amount. 
- Additionally, I have introduced a new string value for the case when the recurring transaction is `paidFor` and is of `INCOME` type

| Before                                                                                                     | After                                                                                                      |
|:----------------------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------:|
| [Old cards video](https://github.com/user-attachments/assets/e2ae0fb3-747a-4402-9d96-dcc4f52c0175)          | [Compact cards video](https://github.com/user-attachments/assets/7935fc05-dcc8-4958-a140-28d38f683b27)       |
| Old description        | Updated description     |

## Risk factors

**What may go wrong if we merge your PR?**
- The paparazzi screenshot for the :screen:transactions was breaking when the `compactModeEnabled` was set to `true`
- I haven't changed any functionality just the UI so logic shouldn't break.
- The new introduced string value `income_received` needs to be edited for the two languages (Have added Todo comments)

**In what cases won't your code work?**
- Should work since its a simple `Bool Feature`

## Does this PR close any GitHub issues? (do not delete)

- Closes #3498

## Troubleshooting GitHub Actions (CI) failures ❌
Pull request checks failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

**Comment by p42rthicle** [comment]
**🚧 WIP**
Have refactored the `TransactionCard` to support compactMode

**Comment by p42rthicle** [comment]
Hi @ILIYANGERMANOV, how do I take care of the failing screenshot test here? 
`:screen:transactions:test` - `TransactionsPaparazziTest` is failing here.

Here is the snapshot of what it expects.


Here, in the empty upcoming transaction card, there is the "deleted" tag that is shown however in my implementation of the compact mode I have omitted tags.
Attaching screen recording of current implementation for your reference.

https://github.com/user-attachments/assets/134477a4-191b-426c-b204-633cd68643cb

Can you help me out so I can proceed? Thanks!

**Comment by p42rthicle** [comment]
@ILIYANGERMANOV 
Could you review this?

**Comment by ILIYANGERMANOV** [comment]
Hey @p42rthicle sorry I missed this PR because the CI was failing and it seemed dangerous to me

**Comment by p42rthicle** [comment]
Yes, I think it's some lint checks that are failing. How do I work on it?

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
Your compact mode isn't showing accounts and categories. Accounts and categories are essential data. Instead of showing one big INCOME/EXPENSE icon let's display the other useful info. Also how does it work for transfers?

**Comment by p42rthicle** [comment]
I purposely omitted the categories and accounts info as I wanted the compact mode to display just bare minimum information. However, if you suggest I can add those in the compact mode. 
What do I omit then in that case? Just the #tags and description (and the INCOME/EXPENSE ICON)? The color on the amount text can suggest if it was an income or an expense
For transfers, I am showing the transfers Icon and amount and no accounts right now. Do you suggest I add those too and make changes?

**Comment by p42rthicle** [comment]
@ILIYANGERMANOV

**Pull request closed without merging**
