### PR TITLE
fix negative transaction issue

### LINKED ISSUE #2718: [BUG] It should not be possible to create negative transactions
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I am able to produce negative transfer, income, and expense transactions! — None of this should be possible as a negative income is an expense, a negative expense is income, and a negative transfer from A -> B, is a positive transfer from B -> A.

Negative transactions results in transaction types (income/expense/transfer) failing to be representative of their purpose, creating confusion.

### To Reproduce

1. Create a new transaction of your choosing, "Add Income", "Add Expense", or "Account Transfer"
2. When prompted to enter the value, open the calculator and type `0 - 75.20`
3. Press "Set"

You have now successfully entered a negative value of 75.20.

### Expected behavior

Whenever a Calculator formula would result in a negative value, the "Set" button should **instead**, create a warning along the lines of "Value cannot be negative".

### Smartphone

Pixel 5

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by vishal2376**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] My code builds and is tested on a real Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

## What's changed?

Screenshot 1 | Screenshot 2
---|---
 | 

Describe with a few bullets **what's new:**
- A toast message will be shown on adding negative amount.

_💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!_

## Risk Factors

**What may go wrong if we merge your PR?**

- a
- b
- c

**In what cases your code won't work?**

- a
- b
- c

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2718 

_Replace `{ISSUE_NUMBER}` with the id/number of the issue that you've fixed._

### CODE REVIEW

**Review by ILIYANGERMANOV — COMMENTED** [review]
Hey @vishal2376 this seems to work well for transactions but will break creating accounts with negative balance. Can you check if accounts with negative balance still works?

**Comment by vishal2376** [comment]
> Hey @vishal2376 this seems to work well for transactions but will break creating accounts with negative balance. Can you check if accounts with negative balance still works?

I can't create account with negative amount
same behaviour as transaction.

I implemented logic within CalculatorModel That's why , it will use same logic whenever we use calculator.

Is there any other approach you want to suggest?

**Comment by ILIYANGERMANOV** [comment]
> > Hey @vishal2376 this seems to work well for transactions but will break creating accounts with negative balance. Can you check if accounts with negative balance still works?
> 
> I can't create account with negative amount same behaviour as transaction.
> 
> I implemented logic within CalculatorModel That's why , it will use same logic whenever we use calculator.
> 
> Is there any other approach you want to suggest?

Accounts should support negative calculations via the Calculator. Add check if it's Account modal. Account modal can go negative, others not

**Comment by vishal2376** [comment]
Hey @ILIYANGERMANOV  i can't find `account` and `transactionType` in the _CalculatorModal_ and _AccountModal_ file . I think i have to add 1 more parameter (mayble isAccount:Boolean) in _AcountModal_ Composable function. But i have to update more than 10 files.

Isn't there any simple solution for this ?

**Comment by ILIYANGERMANOV** [comment]
> Hey @ILIYANGERMANOV  i can't find `account` and `transactionType` in the _CalculatorModal_ and _AccountModal_ file . I think i have to add 1 more parameter (mayble isAccount:Boolean) in _AcountModal_ Composable function. But i have to update more than 10 files.
> 
> Isn't there any simple solution for this ?

Good call. You can add the check in `EditTransactionViewModel` in the save logic and `EditPlannedPaymentViewModel`. This way we should change only 2 files, I suppose. Wdyt?

The other option is `isAccount: Boolean = false` anyway we'll migrate this legacy code so both solutions make sense to me at this point

**Pull request closed without merging**
