### PR TITLE
Fix issue 520

### LINKED ISSUE #520: CSV export broken on locales using comma as decimal separator
So I've just ran into this bug on my new device which I don't want to root, hence no way to transfer all the data from an offline account:

Exporting the CSV in i.e. German locale will mess up all the figures. 118,59€ turns into 11859,00€ etc.
As a workaround, you can change the phone language to English, restart the app and run the export.

Importing does not seem to be affected by locale, so importing a CSV exported in English locale on a device in German locale imports the figures correctly.

### PR DESCRIPTION
**Pull request by Tiihi**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch. => `prod` in this case
- [x] I understand the **[Ivy Developer Guidelines](../docs/Developer-Guidelines.md)**.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully. => i couldnt find any test in prod? tried 2 methods 

## Pull Request Type
Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [ ] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

## Does this PR closes any GitHub Issues?
Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)**.
- Closes #520 

## What's changed?
Describe with a few bullets **what's new:**
- added Locale.US to DecimalFormatter for correct decimal formatting in any device language

### CODE REVIEW

**Review by ILIYANGERMANOV — COMMENTED** [review]
Thank you! This seems like the right step.

You need to also apply the same fix to `fun Double.formatCrypto(): String` in the same file on Line 73.

Can you also attach screen recordings with this build where you test:
- export Ivy Wallet CSV > Import it (cuz I won't have time to actually test it and merge it blindly based on the code changes)

**Comment by Tiihi** [comment]
Hi @ILIYANGERMANOV, 

i added the Locale US also to the cryptoFormatter but this destroys some other code parts.
I think the source of this problem could be the localDecimalSeparator(). Would it be fine if we just set this separator also to US or do we need to implement something to handle both decimal separators (comma, point)?

Example Function (doenst work anymore and returns null):
grafik

After the value gets formatted to crypto we split this value by the localDecimalSeperator and getOrNull the first Index of it. This now results in null when we use german as device language and Locale US in the formatter.

This issue also occurs on the ui because the formatter also handles the values that are getting displayed.

**Comment by ILIYANGERMANOV** [comment]
> Hi @ILIYANGERMANOV,
> 
> i added the Locale US also to the cryptoFormatter but this destroys some other code parts. I think the source of this problem could be the localDecimalSeparator(). Would it be fine if we just set this separator also to US or do we need to implement something to handle both decimal separators (comma, point)?
> 
> Example Function (doenst work anymore and returns null): grafik
> 
> After the value gets formatted to crypto we split this value by the localDecimalSeperator and getOrNull the first Index of it. This now results in null when we use german as device language and Locale US in the formatter.
> 
> This issue also occurs on the ui because the formatter also handles the values that are getting displayed.

Hi @Tiihi, I understand. Would that work - make the the `formatCrypto(usLocale: Boolean = false)` and set the `usLocale = true` only when exporting?

The UI must support the local decimal separator and not hardcode it to US.

**Comment by ILIYANGERMANOV** [comment]
I'm also thinking should we instead modify the code we use when exporting a CSV backup?
Let's not change the code that we use for displaying stuff on the UI - it seems fragile

**Comment by Tiihi** [comment]
> I'm also thinking should we instead modify the code we use when exporting a CSV backup? Let's not change the code that we use for displaying stuff on the UI - it seems fragile

Yeah thats true, i will look tomorrow evening for a better solution that only changes the export logic and not the normal formatting functions that are used across the whole project.

**Comment by ILIYANGERMANOV** [comment]
> > I'm also thinking should we instead modify the code we use when exporting a CSV backup? Let's not change the code that we use for displaying stuff on the UI - it seems fragile
> 
> Yeah thats true, i will look tomorrow evening for a better solution that only changes the export logic and not the normal formatting functions that are used across the whole project.

Awesome - thank you!

**Comment by Tiihi** [comment]
> > > I'm also thinking should we instead modify the code we use when exporting a CSV backup? Let's not change the code that we use for displaying stuff on the UI - it seems fragile
> > 
> > 
> > Yeah thats true, i will look tomorrow evening for a better solution that only changes the export logic and not the normal formatting functions that are used across the whole project.
> 
> Awesome - thank you!

Should i fix this problem now on main-branch with a new pr?
And whats the correct format that should be displayed in the csv for comma and point values?


1.234,25 => current localDecimalSeparator - point
1,234.25 => current localDecimalSeparator  - comma

Do we need the first comma / point when we have a value over thousand?
I mean this confuses me already because normally we dont have a separator in this place?
Wouldnt it make sense to write 1234,50 or 1234.50 to the file and drop the first separator?

**Comment by ILIYANGERMANOV** [comment]
> > > > I'm also thinking should we instead modify the code we use when exporting a CSV backup? Let's not change the code that we use for displaying stuff on the UI - it seems fragile
> > > 
> > > 
> > > Yeah thats true, i will look tomorrow evening for a better solution that only changes the export logic and not the normal formatting functions that are used across the whole project.
> > 
> > 
> > Awesome - thank you!
> 
> Should i fix this problem now on main-branch with a new pr? And whats the correct format that should be displayed in the csv for comma and point values?
> 
> 1.234,25 => current localDecimalSeparator - point 1,234.25 => current localDecimalSeparator - comma
> 
> Do we need the first comma / point when we have a value over thousand? I mean this confuses me already because normally we dont have a separator in this place? Wouldnt it make sense to write 1234,50 or 1234.50 to the file and drop the first separator?

Hey again @Tiihi! Apologies, we're doing a branch cleanup cuz our GitHub has gotten messy (more info at https://t.me/c/1647280565/8169/16707) and deleting `prod` auto-closed your PR 😬 

Yes, you should make the PR to `main` instead - I'll update the CONTRIBUTING guide and PR tempalte, too.

Regarding the CSV format we need to save the numbers in following this format:
- "1234.05"
Using `.` as a separator and **no commas**. We need to follow a similar pattern that `Double.toString()` uses but w/o doing "1^E26" and etc

**Pull request closed without merging**
