### PR TITLE
Fix issue 3171

### LINKED ISSUE #3171: [BUG] Description multiline gets duplicated
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In the latest build (29 apr app-demo.apk) on my phone with Android 13 as OS I noticed that when writing in the description field and entering a new line (enter) the text in the previous line gets duplicated in the next line.

### To Reproduce

1. open expense or income or transfer
2. enter the description
3. press enter
4. the previous line gets duplicated

### Expected behavior

I expect the line to not be repeated when I go to a newline.

### Screenshots

_No response_

### App version

4.6.3 (163) from GitHub

### Smartphone

Samsung Galaxy S20FE, Android 13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by biagio11**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [X] The PR is submitted to the `main` branch.
- [X] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [X] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [X] I confirm that I've run the code locally and everything works as expected.
- [X] 🎬 I've attached a **screenshoot** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?
Before | After
--|--
Screenshot_20240430_181154_Ivy Wallet | Screenshot_20240430_181209_Ivy Wallet

- The line won't get duplicated when enter is pressed.

## Risk Factors

**What may go wrong if we merge your PR?**

- A test case may fail.

**In what cases your code won't work?**

- I don't know.

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #3171 

> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.

> **!Note:** Do **not** link the PR number. Link the number/id of the GitHub Issue from [issues](https://github.com/Ivy-Apps/ivy-wallet/issues).

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

**Comment by biagio11** [comment]
This should fix the issue.

**Review by ILIYANGERMANOV — APPROVED** [review]
LGTM! Ping me after the CI checks pass so we can merge the fix

**Comment by ILIYANGERMANOV** [comment]
Use this guide to fix the CI checks:
https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md

**Comment by ILIYANGERMANOV** [comment]
Detekt error:
home/runner/work/ivy-wallet/ivy-wallet/temp/legacy-code/src/main/java/com/ivy/legacy/ui/component/edit/core/Description.kt:3:1: Unused import [NoUnusedImports]

You need to remove unused imports

**Pull request merged**
