### PR TITLE
Fix issue 2674

### LINKED ISSUE #2674: [FEATURE] Transaction screen - separate Date & Time picker buttons
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues

### What do you want to be added or improved?

As a user, I want to be able to pick only the Date or only the Time of a transaction. Currently, it always asks to set first the date and then the transaction. I want to have separate buttons for doing that.

### Why do you need it?

- It's annoying always to be forced to input both the transaction Date and the transaction time.
- I want to be able to set transaction date and time separately.

### How do you imagine it?

1. On the edit screen one button for "Date" and another for "Time"
2. If I click on "Date" - only the date picker shows.
3. If I click on "Time" - only the time picker shows.

**The UI must scale well on smaller devices!** For example, closed Fold4.

### PR DESCRIPTION
**Pull request by anirudh797**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- 

- [x] The PR is submitted to the `main` branch. Yes

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md). Yes
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md). Yes
- [x] My code builds and is tested on a real Android device. Yes (One plus Nord 2)
- [x] I confirm that I've run the code locally and everything works as expected.

## What's changed?
  Separate Date and Time listener for transactions page.
- When user clicks on Date , Date picker will be shown
- When user clicks on Time , Time Picker will be shown

Describe with a few bullets **what's new:**
- a   Separate Date and Time listener for transactions page.
- b
- c
- d

_💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!_

## Risk Factors

**What may go wrong if we merge your PR?**

- a  Date or Time of transaction not updating ( Not found issue at my end while testing)
- b
- c

**In what cases your code won't work?**

- a Ideally should work for all cases ( updating date or time for  existing transactions or saving LocalTime when creating new Transaction)
- b
- c

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2674 

_Replace `{ISSUE_NUMBER}` with the id/number of the issue that you've fixed._

### CODE REVIEW

**Review by ILIYANGERMANOV — COMMENTED** [review]
Hey @anirudh797 thank you for your PR! 🎉  Can you upload a screen recoding demonstrating the UI/UX of your changes?

**Comment by ILIYANGERMANOV** [comment]
Also try to fix the Detekt errors that are easy to fix and then add a Detekt baseline using:
```
./scripts/detektBaseline.sh
```

**Comment by anirudh797** [comment]
@ILIYANGERMANOV  screen recording https://gemoo.com/tools/upload-video/share/567421131982376960?codeId=vz2w469l9de0r&card=567421127481888768 , will fix detekt errors and update .

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV screen recording https://gemoo.com/tools/upload-video/share/567421131982376960?codeId=vz2w469l9de0r&card=567421127481888768 , will fix detekt errors and update .

Thanks for uploading! Correct me if I'm wrong but the task was about having 2 seprate clickable buttons for "Date" and "Time". When I click "Date" => only date picker opens. When I click "Time" => only time picker opens. Does it work like? I'm just extremly busy these days and can only read/watch between the lines :D

**Comment by anirudh797** [comment]
@ILIYANGERMANOV As per my understanding when user clicks on date text we need to show date picker , and when user clicks on time text we need to show time picker , implemented in this manner. Is that correct?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV As per my understanding when user clicks on date text we need to show date picker , and when user clicks on time text we need to show time picker , implemented in this manner. Is that correct?

Perfect, that's correct! 💯

**Review by ILIYANGERMANOV — APPROVED** [review]
Nice work 💯 Fix Detekt and merge conflicts and we're good to merge 🚀

**Comment by ILIYANGERMANOV** [comment]
If the Detekt errors are hard to fix feel free to use:
```
./scripts/detektBaseline.sh
```

and we're good

**Comment by anirudh797** [comment]
Facing some compatibility issues with script , will let you know once done.

**Comment by ILIYANGERMANOV** [comment]
> ready for merge @ILIYANGERMANOV

Nice work! Merging 🚀

**Pull request merged**
