### PR TITLE
Change Balance Row to use a single Text

### LINKED ISSUE #2712: Change the balance display style in Accounts tab
### Please confirm the following:

- [X] I've checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate issues.
- [X] I've requested a single (only one) feature/change in this issue. It complies with the One Request Per GitHub Issue (ORPGI) rule.
- [X] My issue is well-defined and describes how it should be implemented from UI/UX perspective.

### What do you want to be added or improved?

As a user, I would like to have the account balance value in the Accounts tab more visible and clear. 

The current subscripted hundredths' style makes it a bit unreadable, especially for the balance value converted to the main currency. I personally have a little problem in seeing these small digits in the USD balance line.

### Why do you need it?

- to have the balance easily readable
- would fix the visibility for currency-converted line as shown above

### How do you imagine it?

I think it is as simple as making the hundredths value appear in line with and the same size as the other digits of the balance value. To make them look different, apply a light/thin font style as for the currency code

### PR DESCRIPTION
**Pull request by Adrin7113**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] My code builds and is tested on a real Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

## What's Changed:
-  Changed the BalanceRow Composable to use a single Text for displaying the balance instead of two separate ones for integer and decimal part.
-  Thus making both the integer and decimal parts look uniform in style.

## Risk Factors

**What may go wrong if we merge your PR?**

-  This is only a UI change so hopefully nothing :)

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues/2712)**.

- Closes #2712

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
@Adrin7113 can you please attach a screen recording so we can see the UI/UX and prove that it works?

It must contain accounts with:
- 0 balance
- 100k balance
- 1M balance
- account having a crypto currency as currency, let's say BTC

**Comment by Adrin7113** [comment]
https://github.com/Ivy-Apps/ivy-wallet/assets/112411286/eb309489-4b49-44d9-aa6e-f62e92be57c8

**Comment by Adrin7113** [comment]
> demo.mp4

@ILIYANGERMANOV

**Review by ILIYANGERMANOV — APPROVED** [review]
Thank you @Adrin7113! Sorry for the delayed review 😬 Looks good to me! Just fix the CI errors and we should be good to merge 💯

**Comment by ILIYANGERMANOV** [comment]
@Adrin7113 CI troubleshooting steps can be found in this PR:
https://github.com/Ivy-Apps/ivy-wallet/pull/2761

**Pull request closed without merging**
