### PR TITLE
Fix Issue 520

### LINKED ISSUE #520: CSV export broken on locales using comma as decimal separator
So I've just ran into this bug on my new device which I don't want to root, hence no way to transfer all the data from an offline account:

Exporting the CSV in i.e. German locale will mess up all the figures. 118,59€ turns into 11859,00€ etc.
As a workaround, you can change the phone language to English, restart the app and run the export.

Importing does not seem to be affected by locale, so importing a CSV exported in English locale on a device in German locale imports the figures correctly.

### PR DESCRIPTION
**Pull request by Tiihi**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the
  **[Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

## Pull Request Type
Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [ ] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in all the boxes that apply._

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.
- Closes #520 

## What's changed?
Describe with a few bullets **what's new:**
- the values are getting now handled depending on the localDecimalSeparator
- result format in any device language should be "1078.95"

grafik

### CODE REVIEW

**Comment by Tiihi** [comment]
FYI i will provide tmrw some screen recordings for the export process.

**Comment by Tiihi** [comment]
> Awesome work @Tiihi! The fix LGTM 💯 Yeah, please send the screen recordings and do a smoke test for Export & Import Ivy CSV (make sure to include an account holding BTC or other crypto)
> 
> If everything works, I'll merge it and it'll be live in the next release 🙌

Hi @ILIYANGERMANOV,

here are the recordings for the import / export process in two different device languages (german & english). I also added the two export csv-files to this post. 

I restarted the app between every process and deleted of course the local user data before importing the csv files. I think i also found another bug that appears when i delete the local user data and try to import the files afterwards without restarting the app. The App is stuck after successfully importing the data and i cant continue to set my currency. This Bug doesnt have anything to do with my changes, i also tested this behavior on the current main branch without my changes. I will create a bug ticket if none exists yet.

German Import / Export / CSV File:

https://github.com/Ivy-Apps/ivy-wallet/assets/71343607/d615d615-7c32-412e-9869-d4f1b403ddf6

https://github.com/Ivy-Apps/ivy-wallet/assets/71343607/45af7044-b70c-4fd7-b9ac-a7861dfcba40

[german.csv](https://github.com/Ivy-Apps/ivy-wallet/files/12488503/german.csv)

English Import / Export / CSV File:


https://github.com/Ivy-Apps/ivy-wallet/assets/71343607/0118cdab-d304-4517-ae16-9e507267ade8


https://github.com/Ivy-Apps/ivy-wallet/assets/71343607/6b0fc497-1911-46b5-98eb-2a0efea32b08


[english.csv](https://github.com/Ivy-Apps/ivy-wallet/files/12488505/english.csv)

**Comment by Tiihi** [comment]
Created #2519 for the issue that i discovered while testing this bug fix

**Comment by ILIYANGERMANOV** [comment]
Excellent work! Thanks for raising the bug ticket 🐛 Merging to `main`

**Pull request merged**
