### PR TITLE
Fix issue #1343

### LINKED ISSUE #1343: [TASK] Index item icons by keywords
### Please confirm the following

- [X] I checked [the current issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues) for duplicate problems

### What do you want to be added or improved?

As a core developer, I want to have icons linked by multiple keywords that our users might search them.

## How to?

1. See this file - https://github.com/Ivy-Apps/ivy-wallet/blob/develop/core/ui/src/main/java/com/ivy/core/ui/icon/picker/IconPickerIcons.kt

2. Do it as I did it for a few `ivyIcons`
```kt
private fun ivyIcons(): List<PickerItemUnverified> = listOf(
    SectionDivider("Ivy"),
    Icon("account", keywords = listOf("account", "acc")),
    Icon("category", keywords = listOf("category", "cat")),
    Icon("cash", keywords = listOf("cash", "money")),
    Icon("bank", keywords = listOf("bank")),
    Icon("revolut", keywords = listOf("revolut", "rev")),
    Icon("clothes2", keywords = listOf("clothes")),
    Icon("clothes", keywords = listOf("clothes", "wardrobe")),
    Icon("family", keywords = listOf("family", "home", "couple", "kids")),
    Icon("star", keywords = listOf("star", "favorite")),
    Icon("education", keywords = listOf("education", "school", "university")),
    Icon("fitness", keywords = listOf("fitness", "gym", "workout", "train", "weights")),
    Icon("loan", keywords = listOf("loan", "bill", "note")),
    Icon("orderfood", keywords = listOf("order", "delivery", "box")),
    Icon("orderfood2", keywords = listOf("order", "delivery", "scouter")),
    Icon("pet", keywords = listOf("pet", "dog", "paw")),
    Icon("restaurant", keywords = listOf("restaurant", "eat", "dinner", "food")),
    Icon("selfdevelopment", keywords = listOf("learn", "improve", "level", "grow")),
    // ...
```

3. Do it for as many other icons as you can
4. Note: sync with other contributors working on that so we don't duplicate work.

### Why do you need it?

- We need it to implement a "Search icons" feature.

### How do you imagine it?

_No response_

### PR DESCRIPTION
**Pull request by tarund2302**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `develop` branch.
- [x] I understand the **[Ivy Developer Guidelines](../docs/Developer-Guidelines.md)**.
- [x] I've read the **[Contribution Guidelines](https://github.com/ILIYANGERMANOV/ivy-wallet/blob/main/CONTRIBUTING.md)**.
- [x] The code builds and is tested on an actual Android device.
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] I confirm that I've run Ivy Wallet's UI tests (`androidTest`) and all tests are passing
  successfully.

_Important: Don't worry if you experience flaky UI tests. Just re-run the failed ones again and if they pass => it's all good!_

_Put an `x` in the boxes that apply._
- [x] Demo: Checking checkbox using `[x]`

## Pull Request Type
Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, new lines, etc.)
- [ ] Refactoring (no functional changes, renaming)
- [x] Small improvement (fix typo, UI fine-tune, change color or something small)
- [ ] Gradle Build related changes
- [ ] Dependencies update (updating libraries)
- [ ] Documentation (clarifying comments, KDoc)
- [ ] Tests (Unit, Integration, UI tests)
- [ ] Other (please describe):

_Put an `x` in the boxes that apply._

## Does this PR closes any GitHub Issues?
Check **[Ivy Wallet Issues](https://github.com/ILIYANGERMANOV/ivy-wallet/issues)**.
- Closes #1343 

## What's changed?
Describe with a few bullets **what's new:**
- Added to ivyIcons()
- Added to vueSecurity(), vueShop(), vueSupport()
- Added to vueTransport(), vueType(), vueWeather()

## How to run Ivy Wallet's UI tests (`androidTest`)
**Connect Android Emulator**
- Pixel 5 API 29+ AVD emulator _(recommended)_
- Pixel 3XL API 29+ AVD emulator _(recommended)_
- Large screen physical device _(might also work)_

**Method 1: Android Studio UI**
- Find `com (androidTest)` package
- Right click
- `Run 'Tests in 'com''`

_Note: If you've checked "Compact Middle Packages" the option will appear as `com.ivy.wallet (androidTest)`._

**Method 2: Gradle Wrapper**
- `chmod +x gradlew` (Linux)
- `./gradlew connectedDebugAndroidTest`

**Method 3: Fastlane**
- Install Ruby 2.7
- `bundle install`
- `bundle exec fastlane ui_tests`

### CODE REVIEW

**Comment by ILIYANGERMANOV** [comment]
Hi @tarund2302 your keywords look good to me! Can you fix merge conflicts by accepting what's in `develop`? Then the CI checks will run and we can merge them.

**Comment by tarund2302** [comment]
Hi @ILIYANGERMANOV, how do I accept what's in develop? I clicked "Resolve Conflicts" and I'm confused on what to do further.

**Comment by ILIYANGERMANOV** [comment]
Hi @tarund2302, it's tough from GitHub. In Android Studio you can click "Accept Theirs" when resolving conflicts

**Comment by avinal** [comment]
@tarund2302, you can rebase your branch with develop. It will automatically show you the conflicts and then you can resolve them. Please ping me if you need help with that.

**Comment by ILIYANGERMANOV** [comment]
Thank you very much @avinal! I don't have the time to support @tarund2302 but would really appreciate merging his contribution

**Comment by ILIYANGERMANOV** [comment]
Hi again @tarund2302 the easiest way to fix merge conflicts is to:
1) Save your changes in a new file
```
// region Security (Vue)
private fun vueSecurity(): List<Icon> = listOf(
    Icon("ic_vue_security_eye", keywords=listOf("security", "eye", "vision", "sensor")),
    Icon("ic_vue_security_shield_security", keywords=listOf("security", "shield", "protect", "sensor")),
    Icon("ic_vue_security_key", keywords=listOf("security", "key")),
    Icon("ic_vue_security_alarm", keywords=listOf("security", "alarm", "sensor")),
    Icon("ic_vue_security_lock", keywords=listOf("security", "lock", "sensor")),
    Icon("ic_vue_security_password", keywords=listOf("security", "password", "pass")),
    Icon("ic_vue_security_radar", keywords=listOf("security", "radar", "sensor")),
    Icon("ic_vue_security_shield_person", keywords=listOf("security", "shield", "person")),
    Icon("ic_vue_security_shield", keywords=listOf("security", "shield", "sensor"),
)
// endregion

// region Shop (Vue)
private fun vueShop(): List<Icon> = listOf(
    Icon("ic_vue_shop_cart", keywords=listOf("shop", "cart")),
    Icon("ic_vue_shop_bag", keywords=listOf("shop", "bag")),
    Icon("ic_vue_shop_barcode", keywords=listOf("shop", "barcode", "code")),
    Icon("ic_vue_shop_bag1", keywords=listOf("shop", "bag")),
    Icon("ic_vue_shop_shop", keywords=listOf("shop", "options")),
)
// endregion

// region Support (Vue)
private fun vueSupport(): List<Icon> = listOf(
    Icon("ic_vue_support_star", keywords=listOf("support", "star", "support reaction", "reaction")),
    Icon("ic_vue_support_medal", keywords=listOf("support", "medal", "support reaction", "reaction")),
    Icon("ic_vue_support_dislike", keywords=listOf("support", "dislike", "support reaction", "reaction")),
    Icon("ic_vue_support_like_dislike", keywords=listOf("support", "like", "dislike", "like dislike", "support reaction", "reaction")),
    Icon("ic_vue_support_smileys", keywords=listOf("support", "smileys", "support reaction", "reaction")),
    Icon("ic_vue_support_heart", keywords=listOf("support", "heart", "support reaction", "reaction")),
    Icon("ic_vue_support_like", keywords=listOf("support", "like", "support reaction", "reaction")),
)
// endregion

// region Transport (Vue)
private fun vueTransport(): List<Icon> = listOf(
    Icon("ic_vue_transport_bus", keywords=listOf("transport", "vehicle", "bus")),
    Icon("ic_vue_transport_airplane", keywords=listOf("transport", "vehicle", "airplane", "plane")),
    Icon("ic_vue_transport_train", keywords=listOf("transport", "vehicle", "train", "tram")),
    Icon("ic_vue_transport_ship", keywords=listOf("transport", "vehicle", "ship", "boat", "cruise")),
    Icon("ic_vue_transport_gas", keywords=listOf("transport", "vehicle", "gas", "petrol")),
    Icon("ic_vue_transport_car", keywords=listOf("transport", "vehicle", "car")),
    Icon("ic_vue_transport_car_wash", keywords=listOf("transport", "vehicle","car wash", "wash"))
)
// endregion

// region Type (Vue)
private fun vueType(): List<Icon> = listOf(
    Icon("ic_vue_type_link2", keywords=listOf("type", "link", "attachment")),
    Icon("ic_vue_type_text", keywords=listOf("type", "text", "word")),
    Icon("ic_vue_type_paperclip", keywords=listOf("type", "text", "paperclip", "clip")),
    Icon("ic_vue_type_textalign_left", keywords=listOf("type", "align", "align left")),
    Icon("ic_vue_type_translate", keywords=listOf("type", "translate")),
    Icon("ic_vue_type_textalign_right", keywords=listOf("type", "algin", "align right")),
    Icon("ic_vue_type_link", keywords=listOf("type", "link", "attachment")),
    Icon("ic_vue_type_textalign_center", keywords=listOf("type", "text", "align center")),
    Icon("ic_vue_type_textalign_justifycenter", keywords=listOf("type", "text", "align justify"))
)
// endregion

// region Weather (Vue)
private fun vueWeather(): List<Icon> = listOf(
    Icon("ic_vue_weather_wind", keywords=listOf("weather", "wind", "air")),
    Icon("ic_vue_weather_cloud", keywords=listOf("weather", "cloud")),
    Icon("ic_vue_weather_flash", keywords=listOf("weather", "flash", "lightning", "thunder")),
    Icon("ic_vue_weather_moon", keywords=listOf("weather", "moon")),
    Icon("ic_vue_weather_drop", keywords=listOf("weather", "drop", "rain")),
    Icon("ic_vue_weather_cold", keywords=listOf("weather", "cold", "snow", "hail", "chill")),
    Icon("ic_vue_weather_sun", keywords=listOf("weather", "sun", "warm", "hot"))
)
// endregion
```

2) Delete your fork
3) Fork again
4) Paste the changes
5) PR with no conflicts which I'll merge

**Comment by avinal** [comment]
Hi @ILIYANGERMANOV if this is too urgent, I can fix the conflicts and open a new PR with @tarund2302 as the author of the commits.

**Pull request closed without merging**
