### PR TITLE
Fix Issue #2927

### LINKED ISSUE #2927: [BUG] Balance row text alignment
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Just tried a recent nightly build and the first thing I noticed was a slight value misplacement for the balancerow strings.

### To Reproduce

_No response_

### Expected behavior

Vertically align the value and currency code in the BalanceRow.

### Screenshots

67b8a09c-8a89-45df-9234-dd5fc586a335

### Smartphone

Galaxy S23

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sandeepjak2007**
The excluded Amount issue in the Account tab is fixed

## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?
TBe-1
TBe

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2927 

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
Nice catch @sandeepjak2007 💯 Thanks for the fix! Merging it after the CI pass

**Comment by ILIYANGERMANOV** [comment]
> Hi @sandeepjak2007, the Reorder button is now missing in the Accounts tab. Is this intentional?

That's definitely a regression! Good catch @nvllz 👏 We need #2923 asap

**Comment by sandeepjak2007** [comment]
> Hi @sandeepjak2007, the Reorder button is now missing in the Accounts tab. Is this intentional?

Could this issue be related to my commit? I've noticed no changes to the reorder button. If you come across any discrepancies, could you please post or highlight the specific commit that might have caused the problem?

**Comment by ILIYANGERMANOV** [comment]
> > Hi @sandeepjak2007, the Reorder button is now missing in the Accounts tab. Is this intentional?
> 
> Could this issue be related to my commit? I've noticed no changes to the reorder button. If you come across any discrepancies, could you please post or highlight the specific commit that might have caused the problem?

I think it happened when you update the UI in your first PR but I haven't double checked

**Comment by sandeepjak2007** [comment]
> > Hi @sandeepjak2007, the Reorder button is now missing in the Accounts tab. Is this intentional?
> 
> Could this issue be related to my commit? I've noticed no changes to the reorder button. If you come across any discrepancies, could you please post or highlight the specific commit that might have caused the problem?

It's my fault only. Raising the PR with required screen shot

**Comment by ILIYANGERMANOV** [comment]
Or maybe not, it's probably some simple fix - for some reaso  the button disappeared. Might be before your PRs, too

**Pull request merged**
